#!/bin/bash
sudo rm -f /usr/local/bin/packettracer

# check /etc/profile for existance of PT8HOME
PROFILE="/etc/profile" 

# error exit if file does not exist or unreadable
if [ ! -f $PROFILE ]; then
   exit 0
elif [ ! -r $PROFILE ]; then
   exit 0
fi

# read contents
exec 3<&0
exec 0<$PROFILE
while IFS= read -r line
do
  PT8HOME_FOUND=`expr match "$line" 'PT8HOME'`
  if [ $PT8HOME_FOUND -gt 0 ]; then
	continue
  fi

  EXPORT_FOUND=`expr match "$line" 'export PT8HOME'`
  if [ $EXPORT_FOUND -gt 0 ]; then
	continue
  fi

  CONTENTS="$CONTENTS\n$line"
done
exec 0<&3

sudo echo -e "$CONTENTS" > /etc/profile

exit 0 


