#!/bin/sh -e


# Source debconf library.
. /usr/share/debconf/confmodule

db_fset PacketTracer_900_amd64/show-eula seen false
db_fset PacketTracer_900_amd64/accept-eula seen false
STATE=1 
while [ "$STATE" != 0 -a "$STATE" != 4 ]; do
    case "$STATE" in
    1)
        db_input critical PacketTracer_900_amd64/show-eula || true
    ;;
    2)
        db_input critical PacketTracer_900_amd64/accept-eula || true
    ;;
    3)
        db_get PacketTracer_900_amd64/accept-eula
        if [ "$RET" = "false" ]; then
            exit 1
        fi
    ;;
    esac

    if db_go; then
        STATE=$(($STATE + 1))
    else
        STATE=$(($STATE - 1))
    fi
done

exit 0

