#"firejail", "--profile=/etc/firejail/packettracer.profile", 
version: "3.9"

services:
  mariadb:
    image: mariadb:latest
    container_name: guacamole-mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: guacamole_db
      MYSQL_USER: ptdbuser
      MYSQL_PASSWORD: ptdbpass
      MYSQL_RANDOM_ROOT_PASSWORD: "1"
    volumes:
      - dbdump:/docker-entrypoint-initdb.d

  guacd:
    image: guacamole/guacd
    container_name: pt-guacd
    restart: always

  guacamole:
    image: guacamole/guacamole
    container_name: pt-guacamole
    restart: always
    environment:
      MYSQL_DATABASE: guacamole_db
      MYSQL_USER: ptdbuser
      MYSQL_PASSWORD: ptdbpass
    depends_on:
      - guacd
      - mariadb

  ptvnc:
    build: ./ptweb-vnc
    container_name: ptvnc
    restart: unless-stopped
    cpus: 0.1
    mem_limit: 512m
    oom_kill_disable: true
    ulimits:
      nproc: 512
      nofile:
        soft: 1024
        hard: 1024
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - NET_ADMIN
      - NET_RAW
    entrypoint: ["firejail", "--profile=/etc/firejail/packettracer.profile"]
    command: ["/start"]
    volumes:
      - ./ptweb-vnc/packettracer.profile:/etc/firejail/packettracer.profile:ro
    depends_on:
      - guacd

  nginx:
    image: nginx:latest
    container_name: pt-nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./ptweb-vnc/pt-nginx/www:/usr/share/nginx/html:ro
      - ./ptweb-vnc/pt-nginx/conf:/etc/nginx/conf.d:ro
    depends_on:
      - guacamole

volumes:
  dbdump:

