version: '3.8'

# Example: installer-service + app service pattern using a named volume to persist
# the installed Packet Tracer under /opt/pt. This is an init-style approach:
# 1) Run the `installer` service which mounts the host .deb or a share and writes into the named volume `pt_opt`.
# 2) Start the `ptvnc` service which mounts the `pt_opt` volume and uses the installed files.

services:
  installer:
    image: ptvnc:latest
    container_name: ptvnc-installer
    entrypoint: ["/runtime-install.sh"]
    restart: "no"
    volumes:
      - pt_opt:/opt/pt
      # mount an installer from host into the container; replace the left-hand path with your local .deb
      # - /path/on/host/CiscoPacketTracerXXXX_amd64.deb:/PacketTracer.deb:ro
    environment:
      # Optionally set PT_DEB_PATH or PT_DEB_SHA1
      # PT_DEB_PATH: /PacketTracer.deb
      # PT_DEB_SHA1: <sha1sum>
      VERBOSE: "1"

  ptvnc:
    image: ptvnc:latest
    container_name: ptvnc1
    depends_on:
      - installer
    restart: unless-stopped
    volumes:
      - pt_opt:/opt/pt
    ports:
      - "5901:5901" # example VNC port mapping; adjust as needed
    environment:
      VNC_PASS: "Cisco123"
      VNC_GEOMETRY: "1280x720"
      VNC_DEPTH: "16"

volumes:
  pt_opt:
    name: pt_opt
